//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface VerifyRequestDTO {
  code: string;
}

export interface AuthResponseDTO {
  token?: string;
  refreshToken?: string;
  message?: string;
}

export interface RegisterRequestDTO {
  email: string;
  username: string;
  password: string;
}

export interface RefreshTokenRequestDTO {
  refreshToken?: string;
}

export interface RefreshTokenResponseDTO {
  accessToken?: string;
  refreshToken?: string;
  message?: string;
}

export interface AuthRequestDTO {
  email: string;
  password: string;
}

export interface ReportListDTO {
  id?: number;
  title?: string;
  type?: ReportType;
  categoryName?: string;
  status?: ReportStatus;
  location?: string;
  createdAt?: Date;
}

export enum ReportStatus {
  ACTIVE = "ACTIVE",
  RESOLVED = "RESOLVED",
  EXPIRED = "EXPIRED",
  FLAGGED = "FLAGGED",
  DELETED = "DELETED",
}

export enum ReportType {
  LOST = "LOST",
  FOUND = "FOUND",
}

export interface ReportDetailsDTO {
  id?: number;
  title?: string;
  description?: string;
  type?: ReportType;
  categoryId?: number;
  categoryName?: string;
  status?: ReportStatus;
  location?: string;
  createdAt?: Date;
  expiresAt?: Date;
  userId?: number;
  contactEmail?: string;
  contactPhone?: string;
}
