//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface RegisterRequestDTO {
  email: string;
  username: string;
  password: string;
}

export interface AuthResponseDTO {
  token?: string;
  refreshToken?: string;
  message?: string;
}

export interface RefreshTokenRequestDTO {
  refreshToken?: string;
}

export interface RefreshTokenResponseDTO {
  accessToken?: string;
  refreshToken?: string;
  message?: string;
}

export interface AuthRequestDTO {
  email: string;
  password: string;
}
