// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8082' | (string & {});
};

/**
 * Request body for creating a new report
 */
export type CreateReportRequest = {
    title: string;
    description?: string;
    type: ReportType;
    categoryId: number;
    location?: LocationRequest;
    contactEmail?: string;
    contactPhone?: string;
};

/**
 * Request body for location data
 */
export type LocationRequest = {
    latitude: number;
    longitude: number;
    displayName: string;
    placeId?: string;
    displayPlace?: string;
    displayAddress?: string;
};

export enum ReportType {
    LOST = 'LOST',
    FOUND = 'FOUND'
}

export type ReportDetailsDto = {
    id: number;
    title: string;
    description?: string;
    type: ReportType;
    categoryId: number;
    categoryName: string;
    status: ReportStatus;
    createdAt: string;
    expiresAt?: string;
    userId: number;
    contactEmail?: string;
    contactPhone?: string;
};

export enum ReportStatus {
    ACTIVE = 'ACTIVE',
    RESOLVED = 'RESOLVED',
    EXPIRED = 'EXPIRED',
    FLAGGED = 'FLAGGED',
    DELETED = 'DELETED'
}

export type FcmTokenRequestDto = {
    fcmToken: string;
};

export type VerifyRequestDto = {
    code: string;
};

export type AuthResponseDto = {
    token: string;
    refreshToken: string;
    message?: string;
};

export type RegisterRequestDto = {
    email: string;
    username: string;
    password: string;
};

export type RefreshTokenRequestDto = {
    refreshToken: string;
};

export type RefreshTokenResponseDto = {
    accessToken: string;
    refreshToken: string;
    message?: string;
};

export type AuthRequestDto = {
    email: string;
    password: string;
};

export type ReportListDto = {
    id: number;
    title: string;
    type: ReportType;
    categoryName: string;
    status: ReportStatus;
    createdAt: string;
};

export type ReportCategoryDto = {
    id: number;
    name: string;
};

export type AutoCompleteSuggestionDto = {
    placeId?: string;
    displayName?: string;
    displayPlace?: string;
    displayAddress?: string;
    latitude?: number;
    longitude?: number;
};

export type GetReportsData = {
    body?: never;
    path?: never;
    query?: {
        type?: ReportType;
    };
    url: '/reports';
};

export type GetReportsResponses = {
    /**
     * OK
     */
    200: Array<ReportListDto>;
};

export type GetReportsResponse = GetReportsResponses[keyof GetReportsResponses];

export type CreateReportData = {
    body: CreateReportRequest;
    path?: never;
    query?: never;
    url: '/reports';
};

export type CreateReportResponses = {
    /**
     * Report created successfully
     */
    201: ReportDetailsDto;
};

export type CreateReportResponse = CreateReportResponses[keyof CreateReportResponses];

export type RegisterTokenData = {
    body: FcmTokenRequestDto;
    path?: never;
    query?: never;
    url: '/notifications/register-token';
};

export type RegisterTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type BroadcastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/broadcast';
};

export type BroadcastResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type VerifyData = {
    body: VerifyRequestDto;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type VerifyResponse = VerifyResponses[keyof VerifyResponses];

export type RegisterData = {
    body: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterResponses = {
    /**
     * Verification code sent successfully
     */
    204: void;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshData = {
    body: RefreshTokenRequestDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshResponses = {
    /**
     * OK
     */
    200: RefreshTokenResponseDto;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LoginData = {
    body: AuthRequestDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type SecretData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/secret';
};

export type SecretResponses = {
    /**
     * OK
     */
    200: string;
};

export type SecretResponse = SecretResponses[keyof SecretResponses];

export type GetReportByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/reports/{id}';
};

export type GetReportByIdResponses = {
    /**
     * OK
     */
    200: ReportDetailsDto;
};

export type GetReportByIdResponse = GetReportByIdResponses[keyof GetReportByIdResponses];

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/report-categories';
};

export type GetAllCategoriesResponses = {
    /**
     * Successfully retrieved categories
     */
    200: Array<ReportCategoryDto>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type AutocompleteData = {
    body?: never;
    path?: never;
    query: {
        query: string;
    };
    url: '/locations/autocomplete';
};

export type AutocompleteResponses = {
    /**
     * OK
     */
    200: Array<AutoCompleteSuggestionDto>;
};

export type AutocompleteResponse = AutocompleteResponses[keyof AutocompleteResponses];
