// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8082' | (string & {});
};

export type UpdateUserProfileDto = {
    firstName: string;
    lastName: string;
    phoneNumber?: string;
};

export type UserProfileDto = {
    id: number;
    email: string;
    username: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
    createdAt: string;
    role: string;
};

/**
 * Request body for creating a new report
 */
export type CreateReportRequest = {
    title: string;
    description?: string;
    type: ReportType;
    categoryId: number;
    location?: LocationRequest;
    contactEmail?: string;
    contactPhone?: string;
    images?: Array<ReportImageRequestDto>;
};

/**
 * Request body for location data
 */
export type LocationRequest = {
    osmId: string;
    osmType: string;
};

export type ReportImageRequestDto = {
    imageUrl: string;
    publicId: string;
};

export enum ReportType {
    LOST = 'LOST',
    FOUND = 'FOUND'
}

/**
 * Location data
 */
export type LocationDto = {
    latitude?: number;
    longitude?: number;
    formattedAddress?: string;
};

export type ReportDetailsDto = {
    id: number;
    title: string;
    description?: string;
    type: ReportType;
    categoryId: number;
    categoryName: string;
    status: ReportStatus;
    location: LocationDto;
    createdAt: string;
    expiresAt?: string;
    userId: number;
    userFullName?: string;
    contactEmail?: string;
    contactPhone?: string;
    images?: Array<ReportImageDto>;
};

export type ReportImageDto = {
    id: number;
    imageUrl: string;
    displayOrder: number;
};

export enum ReportStatus {
    ACTIVE = 'ACTIVE',
    RESOLVED = 'RESOLVED',
    EXPIRED = 'EXPIRED',
    FLAGGED = 'FLAGGED',
    DELETED = 'DELETED'
}

export type FcmTokenRequestDto = {
    fcmToken: string;
};

export type VerifyRequestDto = {
    code: string;
};

export type AuthResponseDto = {
    token: string;
    refreshToken: string;
    message?: string;
    role: string;
};

export type RegisterRequestDto = {
    email: string;
    username: string;
    password: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
};

export type RefreshTokenRequestDto = {
    refreshToken: string;
};

export type RefreshTokenResponseDto = {
    accessToken: string;
    refreshToken: string;
    message?: string;
};

export type AuthRequestDto = {
    email: string;
    password: string;
};

export type ReportListDto = {
    id: number;
    title: string;
    type: ReportType;
    categoryName: string;
    status: ReportStatus;
    location: LocationDto;
    createdAt: string;
    thumbnailUrl?: string;
};

export type ReportCategoryDto = {
    id: number;
    name: string;
};

export type NotificationDto = {
    id: number;
    type: NotificationType;
    title: string;
    body: string;
    dataJson?: string;
    isRead: boolean;
    createdAt: string;
};

export enum NotificationType {
    REPORT_CREATED = 'REPORT_CREATED',
    MATCH_FOUND = 'MATCH_FOUND',
    REPORT_EXPIRED = 'REPORT_EXPIRED',
    REPORT_RESOLVED = 'REPORT_RESOLVED'
}

export type PageNotificationDto = {
    totalPages?: number;
    totalElements?: number;
    pageable?: PageableObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    size?: number;
    content?: Array<NotificationDto>;
    number?: number;
    sort?: SortObject;
    empty?: boolean;
};

export type PageableObject = {
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
    unpaged?: boolean;
    offset?: number;
    sort?: SortObject;
};

export type SortObject = {
    sorted?: boolean;
    unsorted?: boolean;
    empty?: boolean;
};

export type UnreadCountDto = {
    count: number;
};

export type AutoCompleteSuggestionDto = {
    osmId?: string;
    osmType?: string;
    displayName?: string;
    displayPlace?: string;
    displayAddress?: string;
};

export type CloudinarySignatureDto = {
    signature: string;
    timestamp: number;
    cloudName: string;
    apiKey: string;
    folder: string;
};

export enum UserRole {
    USER = 'USER',
    ADMIN = 'ADMIN',
    COORDINATOR = 'COORDINATOR'
}

export type UserListDto = {
    id: number;
    email: string;
    username: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
    status: 'ACTIVE' | 'BLOCKED' | 'PARTIALLY_BLOCKED';
    role: UserRole;
    createdAt: string;
};

export type UserDetailsDto = {
    id: number;
    email: string;
    username: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
    status: 'ACTIVE' | 'BLOCKED' | 'PARTIALLY_BLOCKED';
    role: UserRole;
    createdAt: string;
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetProfileResponses = {
    /**
     * User profile retrieved successfully
     */
    200: UserProfileDto;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type UpdateProfileData = {
    body: UpdateUserProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateProfileResponses = {
    /**
     * User profile updated successfully
     */
    200: UserProfileDto;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type GetReportsData = {
    body?: never;
    path?: never;
    query?: {
        type?: ReportType;
    };
    url: '/reports';
};

export type GetReportsResponses = {
    /**
     * OK
     */
    200: Array<ReportListDto>;
};

export type GetReportsResponse = GetReportsResponses[keyof GetReportsResponses];

export type CreateReportData = {
    body: CreateReportRequest;
    path?: never;
    query?: never;
    url: '/reports';
};

export type CreateReportResponses = {
    /**
     * Report created successfully
     */
    201: ReportDetailsDto;
};

export type CreateReportResponse = CreateReportResponses[keyof CreateReportResponses];

export type RegisterTokenData = {
    body: FcmTokenRequestDto;
    path?: never;
    query?: never;
    url: '/notifications/register-token';
};

export type RegisterTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type VerifyData = {
    body: VerifyRequestDto;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type VerifyResponse = VerifyResponses[keyof VerifyResponses];

export type RegisterData = {
    body: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterResponses = {
    /**
     * Verification code sent successfully
     */
    204: void;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshData = {
    body: RefreshTokenRequestDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshResponses = {
    /**
     * OK
     */
    200: RefreshTokenResponseDto;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LoginData = {
    body: AuthRequestDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type MarkAsReadData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type MarkAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type MarkAllAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SecretData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/secret';
};

export type SecretResponses = {
    /**
     * OK
     */
    200: string;
};

export type SecretResponse = SecretResponses[keyof SecretResponses];

export type GetReportByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/reports/{id}';
};

export type GetReportByIdResponses = {
    /**
     * OK
     */
    200: ReportDetailsDto;
};

export type GetReportByIdResponse = GetReportByIdResponses[keyof GetReportByIdResponses];

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/report-categories';
};

export type GetAllCategoriesResponses = {
    /**
     * Successfully retrieved categories
     */
    200: Array<ReportCategoryDto>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/notifications';
};

export type GetNotificationsResponses = {
    /**
     * OK
     */
    200: PageNotificationDto;
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type GetUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/unread-count';
};

export type GetUnreadCountResponses = {
    /**
     * OK
     */
    200: UnreadCountDto;
};

export type GetUnreadCountResponse = GetUnreadCountResponses[keyof GetUnreadCountResponses];

export type AutocompleteData = {
    body?: never;
    path?: never;
    query: {
        query: string;
    };
    url: '/locations/autocomplete';
};

export type AutocompleteResponses = {
    /**
     * OK
     */
    200: Array<AutoCompleteSuggestionDto>;
};

export type AutocompleteResponse = AutocompleteResponses[keyof AutocompleteResponses];

export type GetSignatureData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cloudinary/signature';
};

export type GetSignatureResponses = {
    /**
     * Signature generated successfully
     */
    200: CloudinarySignatureDto;
};

export type GetSignatureResponse = GetSignatureResponses[keyof GetSignatureResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: UserRole;
    };
    url: '/admin/users';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<UserListDto>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: UserDetailsDto;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];
