// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8082' | (string & {});
};

export type UpdateUserProfileDto = {
    firstName: string;
    lastName: string;
    phoneNumber?: string;
};

export type UserProfileDto = {
    id: number;
    email: string;
    username: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
    createdAt: string;
    role: string;
};

export type UpdateMinQuestionsRequestDto = {
    minQuestions: number;
};

export enum QuestionKind {
    TEXT = 'TEXT',
    CHOICE = 'CHOICE'
}

export type UpdateQuestionTemplateRequestDto = {
    prompt: string;
    kind: QuestionKind;
    defaultChoices?: Array<string>;
    isActive: boolean;
};

export type AdminQuestionTemplateDto = {
    id: number;
    categoryId: number;
    categoryName: string;
    prompt: string;
    kind: QuestionKind;
    defaultChoices?: Array<string>;
    isActive: boolean;
    createdAt: string;
};

export type ChallengeQuestionRequestDto = {
    prompt: string;
    kind: QuestionKind;
    source: QuestionSource;
    templateId?: number;
    choices?: Array<string>;
    correctAnswer?: string;
};

/**
 * Request body for creating a new report
 */
export type CreateReportRequest = {
    title: string;
    description?: string;
    type: ReportType;
    categoryId: number;
    location?: LocationRequest;
    contactEmail?: string;
    contactPhone?: string;
    images?: Array<ReportImageRequestDto>;
    questions?: Array<ChallengeQuestionRequestDto>;
};

/**
 * Request body for location data
 */
export type LocationRequest = {
    osmId: string;
    osmType: string;
};

export enum QuestionSource {
    TEMPLATE = 'TEMPLATE',
    CUSTOM = 'CUSTOM'
}

export type ReportImageRequestDto = {
    imageUrl: string;
    publicId: string;
};

export enum ReportType {
    LOST = 'LOST',
    FOUND = 'FOUND'
}

/**
 * Location data
 */
export type LocationDto = {
    latitude?: number;
    longitude?: number;
    formattedAddress?: string;
};

export type ReportDetailsDto = {
    id: number;
    title: string;
    description?: string;
    type: ReportType;
    categoryId: number;
    categoryName: string;
    status: ReportStatus;
    location: LocationDto;
    createdAt: string;
    expiresAt?: string;
    userId: number;
    userFullName?: string;
    hasContactEmail: boolean;
    hasContactPhone: boolean;
    images?: Array<ReportImageDto>;
    challengeId?: number;
};

export type ReportImageDto = {
    id: number;
    imageUrl: string;
    displayOrder: number;
};

export enum ReportStatus {
    ACTIVE = 'ACTIVE',
    MATCHED = 'MATCHED',
    RESOLVED = 'RESOLVED',
    EXPIRED = 'EXPIRED',
    FLAGGED = 'FLAGGED',
    DELETED = 'DELETED'
}

export type CreateChallengeRequestDto = {
    questions: Array<ChallengeQuestionRequestDto>;
};

export type ChallengeDto = {
    id: number;
    reportId: number;
    authorId: number;
    createdAt: string;
    questions: Array<ChallengeQuestionDto>;
};

export type ChallengeQuestionDto = {
    id: number;
    prompt: string;
    kind: QuestionKind;
    source: QuestionSource;
    templateId?: number;
    choices?: Array<string>;
    correctAnswer?: string;
    orderIndex: number;
};

export type FcmTokenRequestDto = {
    fcmToken: string;
};

export type ClaimDetailsDto = {
    id: number;
    challengeId: number;
    reportId: number;
    status: ClaimStatus;
    claimantId: number;
    claimantName?: string;
    message?: string;
    photoUrl?: string;
    submittedAt: string;
    decidedAt?: string;
    answers: Array<ClaimReviewAnswerDto>;
    claimantContact?: RevealedContactDto;
};

export type ClaimReviewAnswerDto = {
    questionId: number;
    prompt: string;
    kind: QuestionKind;
    answerText: string;
    isCorrect?: boolean;
    expectedAnswer?: string;
};

export enum ClaimStatus {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    DECLINED = 'DECLINED',
    WITHDRAWN = 'WITHDRAWN'
}

export type RevealedContactDto = {
    name?: string;
    email: string;
    phone?: string;
};

export type ClaimAnswerRequestDto = {
    questionId: number;
    answerText: string;
};

export type CreateClaimRequestDto = {
    message?: string;
    photoUrl?: string;
    photoPublicId?: string;
    answers: Array<ClaimAnswerRequestDto>;
};

export type ClaimAnswerDto = {
    questionId: number;
    prompt: string;
    answerText: string;
};

export type ClaimDto = {
    id: number;
    challengeId: number;
    reportId: number;
    reportTitle: string;
    status: ClaimStatus;
    message?: string;
    photoUrl?: string;
    submittedAt: string;
    decidedAt?: string;
    answers: Array<ClaimAnswerDto>;
    holderContact?: RevealedContactDto;
};

export type VerifyRequestDto = {
    code: string;
};

export type AuthResponseDto = {
    token: string;
    refreshToken: string;
    message?: string;
    role: string;
};

export type RegisterRequestDto = {
    email: string;
    username: string;
    password: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
};

export type RefreshTokenRequestDto = {
    refreshToken: string;
};

export type RefreshTokenResponseDto = {
    accessToken: string;
    refreshToken: string;
    message?: string;
};

export type AuthRequestDto = {
    email: string;
    password: string;
};

export type CreateQuestionTemplateRequestDto = {
    categoryId: number;
    prompt: string;
    kind: QuestionKind;
    defaultChoices?: Array<string>;
};

export type ReportListDto = {
    id: number;
    title: string;
    type: ReportType;
    categoryName: string;
    status: ReportStatus;
    location: LocationDto;
    createdAt: string;
    thumbnailUrl?: string;
};

export type ReportChallengeDto = {
    id: number;
    finderDisplayName: string;
    createdAt: string;
    questionCount: number;
    myClaimId?: number;
    myClaimStatus?: ClaimStatus;
    attemptsUsed: number;
};

export type ReportContactDto = {
    contactEmail?: string;
    contactPhone?: string;
};

export type ReportCategoryDto = {
    id: number;
    name: string;
    minQuestions: number;
};

export type QuestionTemplateDto = {
    id: number;
    prompt: string;
    kind: QuestionKind;
    defaultChoices?: Array<string>;
};

export type NotificationDto = {
    id: number;
    type: NotificationType;
    title: string;
    body: string;
    dataJson?: string;
    isRead: boolean;
    createdAt: string;
};

export enum NotificationType {
    REPORT_CREATED = 'REPORT_CREATED',
    MATCH_FOUND = 'MATCH_FOUND',
    REPORT_EXPIRED = 'REPORT_EXPIRED',
    REPORT_RESOLVED = 'REPORT_RESOLVED',
    CHALLENGE_CREATED = 'CHALLENGE_CREATED',
    CLAIM_SUBMITTED = 'CLAIM_SUBMITTED',
    CLAIM_APPROVED = 'CLAIM_APPROVED',
    CLAIM_DECLINED = 'CLAIM_DECLINED'
}

export type PageNotificationDto = {
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<NotificationDto>;
    number?: number;
    sort?: SortObject;
    pageable?: PageableObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    empty?: boolean;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    unpaged?: boolean;
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
};

export type SortObject = {
    empty?: boolean;
    unsorted?: boolean;
    sorted?: boolean;
};

export type UnreadCountDto = {
    count: number;
};

export type AutoCompleteSuggestionDto = {
    osmId?: string;
    osmType?: string;
    displayName?: string;
    displayPlace?: string;
    displayAddress?: string;
};

export type CloudinarySignatureDto = {
    signature: string;
    timestamp: number;
    cloudName: string;
    apiKey: string;
    folder: string;
};

export type ClaimantChallengeDto = {
    id: number;
    reportId: number;
    reportTitle: string;
    createdAt: string;
    questions: Array<ClaimantChallengeQuestionDto>;
};

export type ClaimantChallengeQuestionDto = {
    id: number;
    prompt: string;
    kind: QuestionKind;
    choices?: Array<string>;
    orderIndex: number;
};

export type ClaimSummaryDto = {
    id: number;
    status: ClaimStatus;
    claimantName?: string;
    submittedAt: string;
    correctChoiceAnswers: number;
    totalChoiceAnswers: number;
    hasPhoto: boolean;
};

export enum UserRole {
    USER = 'USER',
    ADMIN = 'ADMIN',
    COORDINATOR = 'COORDINATOR'
}

export type UserListDto = {
    id: number;
    email: string;
    username: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
    status: 'ACTIVE' | 'BLOCKED' | 'PARTIALLY_BLOCKED';
    role: UserRole;
    createdAt: string;
};

export type UserDetailsDto = {
    id: number;
    email: string;
    username: string;
    firstName: string;
    lastName: string;
    phoneNumber?: string;
    status: 'ACTIVE' | 'BLOCKED' | 'PARTIALLY_BLOCKED';
    role: UserRole;
    createdAt: string;
};

export type AdminReportDetailsDto = {
    id: number;
    title: string;
    description?: string;
    type: ReportType;
    categoryId: number;
    categoryName: string;
    status: ReportStatus;
    location: LocationDto;
    createdAt: string;
    expiresAt?: string;
    userId: number;
    userFullName?: string;
    contactEmail?: string;
    contactPhone?: string;
    images?: Array<ReportImageDto>;
};

export type AdminClaimListDto = {
    id: number;
    reportId: number;
    reportTitle: string;
    reportType: ReportType;
    challengeId: number;
    challengeAuthorName?: string;
    claimantName?: string;
    status: ClaimStatus;
    submittedAt: string;
    decidedAt?: string;
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetProfileResponses = {
    /**
     * User profile retrieved successfully
     */
    200: UserProfileDto;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type UpdateProfileData = {
    body: UpdateUserProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateProfileResponses = {
    /**
     * User profile updated successfully
     */
    200: UserProfileDto;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type UpdateMinQuestionsData = {
    body: UpdateMinQuestionsRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/report-categories/{id}/min-questions';
};

export type UpdateMinQuestionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateTemplateData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/question-templates/{id}';
};

export type DeactivateTemplateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateTemplateData = {
    body: UpdateQuestionTemplateRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/question-templates/{id}';
};

export type UpdateTemplateResponses = {
    /**
     * OK
     */
    200: AdminQuestionTemplateDto;
};

export type UpdateTemplateResponse = UpdateTemplateResponses[keyof UpdateTemplateResponses];

export type GetReportsData = {
    body?: never;
    path?: never;
    query?: {
        type?: ReportType;
        search?: string;
    };
    url: '/reports';
};

export type GetReportsResponses = {
    /**
     * OK
     */
    200: Array<ReportListDto>;
};

export type GetReportsResponse = GetReportsResponses[keyof GetReportsResponses];

export type CreateReportData = {
    body: CreateReportRequest;
    path?: never;
    query?: never;
    url: '/reports';
};

export type CreateReportResponses = {
    /**
     * Report created successfully
     */
    201: ReportDetailsDto;
};

export type CreateReportResponse = CreateReportResponses[keyof CreateReportResponses];

export type GetChallengesForReportData = {
    body?: never;
    path: {
        reportId: number;
    };
    query?: never;
    url: '/reports/{reportId}/challenges';
};

export type GetChallengesForReportErrors = {
    /**
     * Not a lost report or not the report owner
     */
    400: Array<ReportChallengeDto>;
    /**
     * Report not found
     */
    404: Array<ReportChallengeDto>;
};

export type GetChallengesForReportError = GetChallengesForReportErrors[keyof GetChallengesForReportErrors];

export type GetChallengesForReportResponses = {
    /**
     * Successfully retrieved challenges
     */
    200: Array<ReportChallengeDto>;
};

export type GetChallengesForReportResponse = GetChallengesForReportResponses[keyof GetChallengesForReportResponses];

export type CreateChallengeData = {
    body: CreateChallengeRequestDto;
    path: {
        reportId: number;
    };
    query?: never;
    url: '/reports/{reportId}/challenges';
};

export type CreateChallengeErrors = {
    /**
     * Invalid challenge (wrong report type, own report, too few questions, duplicate)
     */
    400: ChallengeDto;
    /**
     * Report not found
     */
    404: ChallengeDto;
};

export type CreateChallengeError = CreateChallengeErrors[keyof CreateChallengeErrors];

export type CreateChallengeResponses = {
    /**
     * Challenge created
     */
    201: ChallengeDto;
};

export type CreateChallengeResponse = CreateChallengeResponses[keyof CreateChallengeResponses];

export type RegisterTokenData = {
    body: FcmTokenRequestDto;
    path?: never;
    query?: never;
    url: '/notifications/register-token';
};

export type RegisterTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeclineClaimData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/claims/{id}/decline';
};

export type DeclineClaimErrors = {
    /**
     * Not the challenge author or claim already decided
     */
    400: ClaimDetailsDto;
    /**
     * Claim not found
     */
    404: ClaimDetailsDto;
};

export type DeclineClaimError = DeclineClaimErrors[keyof DeclineClaimErrors];

export type DeclineClaimResponses = {
    /**
     * Claim declined
     */
    200: ClaimDetailsDto;
};

export type DeclineClaimResponse = DeclineClaimResponses[keyof DeclineClaimResponses];

export type ApproveClaimData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/claims/{id}/approve';
};

export type ApproveClaimErrors = {
    /**
     * Not the challenge author or claim already decided
     */
    400: ClaimDetailsDto;
    /**
     * Claim not found
     */
    404: ClaimDetailsDto;
};

export type ApproveClaimError = ApproveClaimErrors[keyof ApproveClaimErrors];

export type ApproveClaimResponses = {
    /**
     * Claim approved
     */
    200: ClaimDetailsDto;
};

export type ApproveClaimResponse = ApproveClaimResponses[keyof ApproveClaimResponses];

export type GetClaimsForChallengeData = {
    body?: never;
    path: {
        challengeId: number;
    };
    query?: never;
    url: '/challenges/{challengeId}/claims';
};

export type GetClaimsForChallengeErrors = {
    /**
     * Not the challenge author
     */
    400: Array<ClaimSummaryDto>;
    /**
     * Challenge not found
     */
    404: Array<ClaimSummaryDto>;
};

export type GetClaimsForChallengeError = GetClaimsForChallengeErrors[keyof GetClaimsForChallengeErrors];

export type GetClaimsForChallengeResponses = {
    /**
     * Successfully retrieved claims
     */
    200: Array<ClaimSummaryDto>;
};

export type GetClaimsForChallengeResponse = GetClaimsForChallengeResponses[keyof GetClaimsForChallengeResponses];

export type SubmitClaimData = {
    body: CreateClaimRequestDto;
    path: {
        challengeId: number;
    };
    query?: never;
    url: '/challenges/{challengeId}/claims';
};

export type SubmitClaimErrors = {
    /**
     * Invalid claim (own challenge, missing answers, attempts used up)
     */
    400: ClaimDto;
    /**
     * Challenge not found
     */
    404: ClaimDto;
    /**
     * Daily claim limit reached
     */
    429: ClaimDto;
};

export type SubmitClaimError = SubmitClaimErrors[keyof SubmitClaimErrors];

export type SubmitClaimResponses = {
    /**
     * Claim submitted
     */
    201: ClaimDto;
};

export type SubmitClaimResponse = SubmitClaimResponses[keyof SubmitClaimResponses];

export type VerifyData = {
    body: VerifyRequestDto;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type VerifyResponse = VerifyResponses[keyof VerifyResponses];

export type RegisterData = {
    body: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterResponses = {
    /**
     * Verification code sent successfully
     */
    204: void;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshData = {
    body: RefreshTokenRequestDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshResponses = {
    /**
     * OK
     */
    200: RefreshTokenResponseDto;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LoginData = {
    body: AuthRequestDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetTemplatesData = {
    body?: never;
    path?: never;
    query?: {
        categoryId?: number;
    };
    url: '/admin/question-templates';
};

export type GetTemplatesResponses = {
    /**
     * OK
     */
    200: Array<AdminQuestionTemplateDto>;
};

export type GetTemplatesResponse = GetTemplatesResponses[keyof GetTemplatesResponses];

export type CreateTemplateData = {
    body: CreateQuestionTemplateRequestDto;
    path?: never;
    query?: never;
    url: '/admin/question-templates';
};

export type CreateTemplateResponses = {
    /**
     * OK
     */
    200: AdminQuestionTemplateDto;
};

export type CreateTemplateResponse = CreateTemplateResponses[keyof CreateTemplateResponses];

export type MarkAsReadData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type MarkAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type MarkAllAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMyClaimsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/claims';
};

export type GetMyClaimsResponses = {
    /**
     * Successfully retrieved claims
     */
    200: Array<ClaimDto>;
};

export type GetMyClaimsResponse = GetMyClaimsResponses[keyof GetMyClaimsResponses];

export type SecretData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/secret';
};

export type SecretResponses = {
    /**
     * OK
     */
    200: string;
};

export type SecretResponse = SecretResponses[keyof SecretResponses];

export type GetReportByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/reports/{id}';
};

export type GetReportByIdResponses = {
    /**
     * OK
     */
    200: ReportDetailsDto;
};

export type GetReportByIdResponse = GetReportByIdResponses[keyof GetReportByIdResponses];

export type RevealContactData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/reports/{id}/contact';
};

export type RevealContactResponses = {
    /**
     * OK
     */
    200: ReportContactDto;
};

export type RevealContactResponse = RevealContactResponses[keyof RevealContactResponses];

export type GetMyReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports/mine';
};

export type GetMyReportsResponses = {
    /**
     * OK
     */
    200: Array<ReportListDto>;
};

export type GetMyReportsResponse = GetMyReportsResponses[keyof GetMyReportsResponses];

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/report-categories';
};

export type GetAllCategoriesResponses = {
    /**
     * Successfully retrieved categories
     */
    200: Array<ReportCategoryDto>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type GetQuestionTemplatesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/report-categories/{id}/question-templates';
};

export type GetQuestionTemplatesErrors = {
    /**
     * Category not found
     */
    404: Array<QuestionTemplateDto>;
};

export type GetQuestionTemplatesError = GetQuestionTemplatesErrors[keyof GetQuestionTemplatesErrors];

export type GetQuestionTemplatesResponses = {
    /**
     * Successfully retrieved question templates
     */
    200: Array<QuestionTemplateDto>;
};

export type GetQuestionTemplatesResponse = GetQuestionTemplatesResponses[keyof GetQuestionTemplatesResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/notifications';
};

export type GetNotificationsResponses = {
    /**
     * OK
     */
    200: PageNotificationDto;
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type GetUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/unread-count';
};

export type GetUnreadCountResponses = {
    /**
     * OK
     */
    200: UnreadCountDto;
};

export type GetUnreadCountResponse = GetUnreadCountResponses[keyof GetUnreadCountResponses];

export type AutocompleteData = {
    body?: never;
    path?: never;
    query: {
        query: string;
    };
    url: '/locations/autocomplete';
};

export type AutocompleteResponses = {
    /**
     * OK
     */
    200: Array<AutoCompleteSuggestionDto>;
};

export type AutocompleteResponse = AutocompleteResponses[keyof AutocompleteResponses];

export type GetSignatureData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cloudinary/signature';
};

export type GetSignatureResponses = {
    /**
     * Signature generated successfully
     */
    200: CloudinarySignatureDto;
};

export type GetSignatureResponse = GetSignatureResponses[keyof GetSignatureResponses];

export type GetClaimDetailsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/claims/{id}';
};

export type GetClaimDetailsErrors = {
    /**
     * Not the challenge author
     */
    400: ClaimDetailsDto;
    /**
     * Claim not found
     */
    404: ClaimDetailsDto;
};

export type GetClaimDetailsError = GetClaimDetailsErrors[keyof GetClaimDetailsErrors];

export type GetClaimDetailsResponses = {
    /**
     * Successfully retrieved claim
     */
    200: ClaimDetailsDto;
};

export type GetClaimDetailsResponse = GetClaimDetailsResponses[keyof GetClaimDetailsResponses];

export type GetChallengeData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/challenges/{id}';
};

export type GetChallengeErrors = {
    /**
     * Not allowed to answer this challenge
     */
    400: ClaimantChallengeDto;
    /**
     * Challenge not found
     */
    404: ClaimantChallengeDto;
};

export type GetChallengeError = GetChallengeErrors[keyof GetChallengeErrors];

export type GetChallengeResponses = {
    /**
     * Successfully retrieved challenge
     */
    200: ClaimantChallengeDto;
};

export type GetChallengeResponse = GetChallengeResponses[keyof GetChallengeResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: UserRole;
    };
    url: '/admin/users';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<UserListDto>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: UserDetailsDto;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetReportById1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/reports/{id}';
};

export type GetReportById1Responses = {
    /**
     * OK
     */
    200: AdminReportDetailsDto;
};

export type GetReportById1Response = GetReportById1Responses[keyof GetReportById1Responses];

export type GetClaimsData = {
    body?: never;
    path?: never;
    query?: {
        status?: ClaimStatus;
    };
    url: '/admin/claims';
};

export type GetClaimsResponses = {
    /**
     * OK
     */
    200: Array<AdminClaimListDto>;
};

export type GetClaimsResponse = GetClaimsResponses[keyof GetClaimsResponses];
